apiVersion: batch/v1
kind: Job
metadata:
  name: download-service
spec:
  template:
    metadata:
      name: download-service
    spec:
      containers:

      - name: download-service
        image: sadeghhayeri/live-stream:download-service
        volumeMounts:
        - name: nfs
          mountPath: '/nfs'
        env:
        - name: URL
          value: 'https://test-vod.arvancloud.com/default_vod_channel/4k.mp4'
        - name: OUTPUT
          value: 'nfs/4k.mp4'

      restartPolicy: OnFailure
      volumes:
      - name: nfs
        nfs:
          server: '192.168.224.194'
          path: '/'
          readOnly: false
