apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-service
spec:
  selector:
    matchLabels:
      app: stream-service
  replicas: 1
  template:
    metadata:
      labels:
        app: stream-service
    spec:
      containers:
      - name: stream-service
        image: sadeghhayeri/live-stream:stream-service
        volumeMounts:
        - name: nfs
          mountPath: '/nfs'
        ports:
        - name: index
          containerPort: 80
        - name: hls
          containerPort: 1935
      volumes:
      - name: nfs
        nfs:
          server: '172.17.0.5'
          path: '/'
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: stream-service
  labels:
    run: stream-service
spec:
  ports:
  - name: index
    port: 80
    protocol: TCP
  - name: hls
    port: 1935
    protocol: TCP
  selector:
    run: stream-service
  type: LoadBalancer
